name: Release
on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment:
      name: PyPi

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: 3.12
      - uses: taiki-e/install-action@v2
        with:
          tool: just,uv

      - name: "Run install deps"
        run: "just bootstrap"
      - name: "Build and release"
        run: |
          poetry build
          uv run python -m twine check dist/*
          uv run python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
