name: Release
on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment: release

    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: 3.12
      - name: "Install uv"
        run: "pip install uv"
      - name: "Run install deps"
        run: "just bootstrap"
      - name: "Build and release"
        run: "just release"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
